site_name: DriConfig
site_description: Python class to read from .yaml config files
strict: true

theme:
  name: material
  custom_dir: docs/theme
  language: en
  favicon: img/dribia-favicon-120x120.png
  logo: img/logo_dribia_d_blanc.png
repo_name: dribia/driconfig
repo_url: https://github.com/dribia/driconfig
edit_uri: ''
nav:
  - Welcome to DriConfig: index.md
  - Installation: install.md
  - Usage:
    - usage/introduction.md
    - usage/configdict.md
    - usage/nested_models.md
  - Contribute: contribute.md
extra_css:
- stylesheets/extra.css

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- codehilite
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed
